services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Demoniqus\RedisBundle\Service\CacheService:
    tags:
      - !php/const Demoniqus\CacheBundle\Interfaces\BundleConstantsModelInterface::CACHE_SERVICE_TAG

  Demoniqus\RedisBundle\Factory\ConnectionsFactory: ~

  Demoniqus\RedisBundle\Factory\ConnectionsFactoryInterface: '@Demoniqus\RedisBundle\Factory\ConnectionsFactory'
